language: node_js
node_js:
- "7"
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_11f5177cae3d_key -iv $encrypted_11f5177cae3d_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
before_script:
- npm install
after_success:
- test $TRAVIS_BRANCH = "master" && npm run build
- scp -o StrictHostKeyChecking=no dist.tar $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
- ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh
- rm dist.tar
env:
  global:
  - secure: eCCgPlfqeuB+EnJLyuh59mMeROV6A9dTyg+9t3h1yESBIHJUar3J1aX0/JJ1Y33KIrSXr82E0XjpY12xktW5Zs4sQUrq42WmFy5AihyK1FGwez51DTTnh7jF41P5zWVq/dt1zWM/GIpLrf/MVz6pX9FO2MlDRoRs9ko9mW1tj6nVI+h0PTH5WVQ3oMhv150dPN+VF54qTLYESevJUNWbd1xCh15F1anbk3dnJb+g9WIaUneUROWyW8SJ+HpQ6AZMOwdAKY0hMKI3+a/IP2I90ROChTTWfDpPU6Q3ctKhK+hvpZO1htE8nBK75Jr9ruJujSX2i+ibwYJKr7vvwTWm2HeKAqEAzIpmPSa67Tk2g9c99lgUS/WMYAG7rD+a7UwysSLcBhRySKFLjIL2esH/arH+TXjE+PKjxt0zysf5InMJJrvAGrT5abG7ZEaTjzPmex2bJj7gAKbnxhBWHvqD0u0M/Ipr16FEw6s0OYtKxkt6XJx1w6Hou2EFDlaB22K8oMBc4iXzqXAQkoXY095rbr17FYqDHVCUd6Hf0C/+PsfF6UtAqaJ9jFiq3jODoFicsK8vFKFT48/MSCES4WyjPDA0Lr5J04nLTfcuKAnlkBo5Hn+2iF7mQiXHP3XL/UeUsSHFtgdHJXSQIT+LoWPhUGrRKvac7ffS3CnW5TVK3vs=
  - secure: IkQl41dXEIQk34iNXWz/3zI23xOHUuvQgSK8dWL1F5xSms/y65tJZg1OAsXfrPNU+e9QQfKO7l9bbJShYkI1zCJawlZ30XnZMeL2067KrodF3oCteHt2ZqvhXGPr6zyvBB7DgZOLto/LUMSQC21RGvzLQ3hVmJV3t6S24tGTM1a/fhl/S1Ne5YzsFDhH8tKsB0EwEqos6tOVkbV8Uf4yKznEOCA3GSRZcZMo9RlcdLsCGnJtLfUZXzUWoiBGInNuKb5wt3o49nQTQY2Pt7muJdE5+GA5zIPpg57WeaGaU9MRHoQCjvbIDqnoWBh4xbcvG5Dxr+RHryEhOMF0qAkt7P+xn4quZuMb2+tZs+fMMAiZokvJ8aS/mZNBvQSWk4R9gHyd1n79AzyILgEMipD9HyL/yaQt92WCVJKKY4kbMMWP7E302J4QnqZBCikubLejGp4nHK3Pc2JN5/Y97zhK0v9N6PkNmDdlpFTaTEsh4Xb8GF1BOjtNc8vxYxQ/rb0z9xs2Zcq45lw91+/lSHSMj4CiaOQXyPsXKuRf2DreOH0Zy8e4lm7aDgYJBMdVCqlcgM+Ww68dwPsItmAM1tP1x0fGgqk/w1cEko2dv88St7rXHMlrumacCr3xOQWpbduKMgg01F1MTg8mb3axpd/kTOk+5FyJdc3ckB6jEzYkvMo=
  - secure: v8UCaWEoxevzk61WTrFSbvYl5UjSsp3T/N2Ubj1onhaHrIEDbiaVz3iCD9/x0Mu/IOAuTPycJku9g6W6JfdOTidwjlb9ID1UFRH+NHr6vMsQbat80MyK2IcaukEm3ZtJsyF2GMhgb3jNIldRRQzMQbXxrqRUmWi+TWwaTH9BzSDk4CZOT0TzHu1dcTCYn72MWJyn8qKzAG2TtjyHwjmT3y0Jngwem+XYbChyGziFinDm+4v8biy5KMFl1hFLN3B4XPxthcu9eaO+X9zhAexwkVtsjqVR+NQHqPc1/zQZqYXtAk/6gcJuGHceTgX60PlU4xRJC5ntwugWDbapeY6h99Ki6PL6ikfUMdA1ifV4VhvJ9zVwe9YENNGBKYmOz/P8pG+ODlwpK3/J2SmyhcieSWPQ5hmVeWClUN17QKWis8edYoTb+VoiQidkwAmWNcHLR3tlhr8fmRNdr2rKZ+sGE0BK67qgDVgb3R4kcBvLrGsOiNoVlwSimL8+lofL7+hAPgSxPP5e9WXWhOZYNqhriLyE8zWkkQbIzsoKjKghZmmnsH/3M3OxoNNsj+gui3Aj8FqQzgPLWvj2LGPXBiBVOr4R7nB3bcY65UHkxiKEVjtv+rdiQFzqkO8MEcJTBejEgCN5GaK3ijbv5R2ETEt42UxruJPS25YtcImi6tnSnHc=
